# Generated by Django 2.0.3 on 2019-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=1024)),
                ('condition', models.CharField(max_length=1024)),
                ('winner', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1024)),
                ('game', models.CharField(max_length=1024)),
                ('target', models.CharField(max_length=1024)),
                ('user_identifier', models.CharField(max_length=1024)),
                ('condition', models.CharField(max_length=1024)),
                ('nickname', models.CharField(max_length=1024)),
            ],
        ),
    ]
