# Generated by Django 2.0.3 on 2019-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kills',
            field=models.IntegerField(default=0),
        ),
    ]
