# Generated by Django 2.0.3 on 2019-05-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killer', '0002_auto_20190518_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-kills']},
        ),
    ]
