# Generated by Django 2.2 on 2019-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer', '0003_auto_20190503_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=1024)),
                ('condition', models.CharField(max_length=1024)),
                ('winner', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='kills',
            field=models.IntegerField(default=0),
        ),
    ]
