# Generated by Django 2.2 on 2019-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killer', '0004_auto_20190518_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
